version: "3.8"
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - "images:/ca_assessment/images/"
      - "database:/ca_assessment/data/db"
volumes:
  images:
  database: